### ISSUE TITLE
calculationsHistory not updating since December 5

### ISSUE THREAD

**Issue by jgrizzled** [melonproject/melon-subgraph#11]
fundCalculationsHistories and fund{calculationsHistory} have not been updated since at least December 5, 2019. To reproduce, send the following query to:

> https://api.thegraph.com/subgraphs/name/melonproject/melon

```
query {
  fundCalculationsHistories(first: 1, orderBy:timestamp, orderDirection: desc) {
    timestamp
  }
}
```

current output:
```
"fundCalculationsHistories": [
  {
    "timestamp": "1575543687"
  }
]
```
The above timestamp resolves to **2019-12-05 04:01**

Impact: unable to use TheGraph Melon subgraph for recent fund data

Let me know if I can provide further info. Thanks!

**Comment by iherger** [comment]
Thanks for bringing this up.

This is caused by a change of the smart contract API of Kyber last week (related to the Istanbul fork).

We are actively looking into this, and will communicate as soon as we have more information.

**Comment by fubhy** [comment]
This has been resolved on the subgraph. Blog post related to the issues due to the fork and kyber network migration following.
